[package]
name = "edlint_config"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
globset.workspace = true
serde_yaml.workspace = true
indexmap = { version = "2", features = ["serde"] }

[[bin]]
name = "generate-schema"
path = "src/bin/generate_schema.rs"


[lib]
path = "src/lib.rs"
